/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:769c741a-c367-4faa-894f-cf00d59d4de2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_nwCUvlRjr",
    "aws_user_pools_web_client_id": "6366b1nafc05ndvlv4hvvf44as",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://cbek4qg2jzdlnmfyjc6trfgljm.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ghgcsjhasnb5pdgftmkvvar4iu",
    "aws_user_files_s3_bucket": "amplifyapp90b3d822cc7f4a60a91462c271315d1d150828-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
