/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:a4844540-93a9-4490-8902-36f93c039cd8",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_NtEE3luJn",
    "aws_user_pools_web_client_id": "4h6nq8faqudg1na9c4t06qgg3",
    "oauth": {}
};


export default awsmobile;
